name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Build Docker Image
      run: docker build -t mi-api .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'mi-api'
        format: 'table'
        exit-code: '1'  # Haz que falle si Trivy detecta vulnerabilidades
        ignore-unfixed: true
