name: MI-API CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-lint-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Lint y pruebas
      - run: npm ci
      - run: npm run lint
      - run: npm test

      # Construcción de imagen Docker
      - uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t mi-api:latest .

      # Escaneo de seguridad con Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mi-api:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

